import type { LangCode } from './i18n'

const en = {
  services: {
    airport: 'Airport Transfer',
    hourly: 'Hourly Chauffeur',
    city: 'City Trip',
    day: 'Day Service',
    oneWay: 'One Way Ride',
  },
  dialogLabel: 'booking',
  tripDetails: 'Trip Details',
  tripSubtitle: 'Tell us where and when you need your ride.',
  arrival: 'Arrival',
  departure: 'Departure',
  pickupAirport: 'Pickup Airport',
  dropOffAirport: 'Drop-off Airport',
  selectAirport: 'Select Airport',
  pickupLocation: 'Pickup Location',
  selectPickup: 'Select pickup location',
  destination: 'Destination',
  dropOff: 'Destination',
  optionalDropOff: 'Drop-off Location (Optional)',
  selectDropOff: 'Select drop-off location',
  enterDestination: 'Enter destination',
  pickupDate: 'Pickup Date',
  flightDate: 'Flight Date',
  pickupTime: 'Pickup Time',
  timePicker: {
    timeFormat: 'Time format', twelveHour: '12 hour', twentyFourHour: '24 hour', period: 'AM or PM',
    hour: 'Hour', minute: 'Minute', editHour: 'Choose hour', editMinute: 'Choose minutes',
    selectHour: 'Select hour · Arrow keys also work', selectMinute: 'Select minutes · Arrow keys also work',
    selectedHour: (value: number, period?: string) => `Selected hour ${value}${period ? ` ${period}` : ''}`,
    selectedMinute: (value: number) => `Selected minute ${value}`,
  },
  flightNumber: 'Flight Number',
  flightExample: 'e.g. PK-753',
  from: 'From',
  to: 'To',
  flightRoutePreview: 'Flight route preview',
  selectDuration: 'Select Duration',
  hours: 'hours',
  included: 'included',
  needMore: 'Need more than 2 hours?',
  chooseDayOption: 'Choose Half Day or Full Day options',
  bookingDuration: 'Booking Duration',
  halfDay: 'Half Day',
  fullDay: 'Full Day',
  upTo4Hours: 'Up to 4 hours',
  upTo10Hours: 'Up to 10 hours',
  bookingQuestion: 'Are you making this booking for yourself or a guest?',
  forMyself: 'For Myself',
  selfTravel: "I'll be travelling",
  forGuest: 'For a Guest',
  guestTravel: 'Someone else will be travelling',
  yourDetails: 'Your Details',
  enterYourDetails: 'Please enter your contact details.',
  guestDetails: 'Guest Details',
  enterGuestDetails: "Please enter your guest's details",
  fullName: 'Full Name',
  namePlaceholder: 'Name',
  guestName: 'Guest name',
  phoneNumber: 'Phone Number',
  emailAddress: 'Email Address',
  back: 'Back',
  continue: 'Continue',
  km: 'km',
  validation: {
    required: 'This field is required.',
    email: 'Enter a valid email address.',
    phone: 'Enter at least 8 digits.',
    characters: (count: number) => `Enter at least ${count} characters.`,
    cardNumber: 'Card number must contain 16 digits.',
    cardName: 'Enter at least 2 characters.',
    expiry: 'Use MM/YY format.',
    cvv: 'Enter 3 or 4 digits.',
  },
  calendar: {
    locale: 'en-GB',
    monthLocale: 'en-US',
    weekdays: ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'],
    label: 'calendar',
  },
  airports: [
    'King Khalid International Airport (RUH)',
    'King Abdulaziz International Airport (JED)',
    'King Fahd International Airport (DMM)',
    'Prince Mohammad bin Abdulaziz International Airport (MED)',
  ],
  locations: ['Riyadh', 'Jeddah', 'Dammam', 'Makkah', 'Madinah', 'Al Khobar', 'Tabuk', 'Hail', 'Abha', 'Yanbu', 'Taif', 'Jizan', 'Al-Ula', 'Najran', 'Al Baha'],
  selectRide: 'Select Your Ride',
  selectRideSubtitle: 'Choose your preferred vehicle and provide passenger details.',
  chooseCategory: 'Choose the category that best fits your journey.',
  categories: [
    { name: 'First Class', copy: 'Efficient transportation for daily commutes and short city trips.' },
    { name: 'Business Class', copy: 'Premium sedans with extra legroom, tailored for business.' },
    { name: 'Van', copy: 'Chauffeur-driven MPVs for groups with ample luggage.' },
    { name: 'Sedan', copy: 'Luxury sedans featuring leather privacy glass.' },
    { name: 'SUV', copy: 'Chauffeur-driven SUVs for groups with ample luggage.' },
  ],
  availableVehicles: (category: string) => `Available ${category} vehicles.`,
  passengersAndBags: '2 passengers and 4 bags',
  reviewBooking: 'Review Your Booking',
  pickup: 'Pickup',
  summaryDestination: 'Destination',
  summaryDropOff: 'Drop Off',
  summaryLabels: {
    flight: 'Flight', flightDate: 'Flight Date', pickupDate: 'Pickup Date', pickupTime: 'Pickup Time',
    duration: 'Duration', journey: 'Journey', category: 'Category', vehicle: 'Vehicle',
  },
  summaryValues: { city: 'City Trip', oneWay: 'One Way' },
  addresses: {
    kingFahd: 'King Fahd Road, Riyadh', riyadhFront: 'Riyadh Front, Riyadh',
    riyadh: 'Riyadh, Saudi Arabia', jeddah: 'Jeddah, Saudi Arabia', airport: 'Riyadh International Airport, RUH',
  },
  fareSummary: 'Fare Summary',
  fareSubtitle: {
    airport: 'Your fare for this airport transfer.', hourly: 'Your fare for this hourly booking.',
    city: 'Your fare for this City Trip.', day: 'Your fare for this day service.', oneWay: 'Your fare for this one-way ride.',
  },
  fareLabels: {
    airport: 'Transfer Fare', hourly: 'Hourly Fare', city: 'Journey Fare', day: 'Day Service Fare', oneWay: 'Ride Fare',
  },
  serviceFee: 'Service Fee',
  airportService: 'Airport Service',
  vat: 'VAT (15%)',
  totalFare: 'Total Fare',
  paymentMethod: 'Payment Method',
  cardNumber: 'Card Number',
  cardName: 'Name on Card',
  cardNamePlaceholder: 'Sultan Ali',
  expiryDate: 'Expiry Date',
  cvv: 'CVV',
  secureVerification: 'Secure verification',
  otpTitle: 'Enter the one-time password sent to your phone.',
  otpSent: "We've sent a 6-digit verification code.",
  otpDigit: (digit: number) => `OTP digit ${digit}`,
  otpResend: "Didn't get the code? Resend in 00:45",
  resendOtp: 'Resend OTP',
  contactDetails: 'Your Contact Details',
  yourName: 'Full Name',
  yourEmail: 'Email Address',
  yourPhone: 'Phone Number',
  baseFare: 'Base Fare',
  requestReceived: 'Request Received',
  receivedTitle: "We've received your booking request.",
  receivedBody: 'Your booking confirmation and details will be sent to your email address.',
  bookingReference: 'Booking Reference',
  trackJourney: 'App Coming Soon',
  trackBody: 'The White Line app is coming soon.',
  downloadOn: 'Download on the',
  getItOn: 'Get it on',
  downloadApp: 'Done',
  mobileAppAlt: 'White Line mobile app',
  closeLabel: 'Close booking dialog',
  cancelTitle: 'Cancel your booking?',
  cancelBody: "All the information you've entered will be lost. Are you sure you want to leave?",
  cancelKeepBooking: 'Continue Booking',
  cancelYes: 'Yes, Cancel',
}

const ar: typeof en = {
  services: {
    airport: 'توصيل المطار',
    hourly: 'سائق بالساعة',
    city: 'رحلة المدن',
    day: 'خدمة يومية',
    oneWay: 'مشوار باتجاه واحد',
  },
  dialogLabel: 'حجز',
  tripDetails: 'تفاصيل المشوار',
  tripSubtitle: 'علّمنا من وين ومتى تبي مشوارك.',
  arrival: 'وصول',
  departure: 'مغادرة',
  pickupAirport: 'مطار الاستقبال',
  dropOffAirport: 'مطار التوصيل',
  selectAirport: 'اختر المطار',
  pickupLocation: 'موقع الانطلاق',
  selectPickup: 'اختر موقع الانطلاق',
  destination: 'الوجهة',
  dropOff: 'الوجهة',
  optionalDropOff: 'موقع التوصيل (اختياري)',
  selectDropOff: 'اختر موقع التوصيل',
  enterDestination: 'اكتب الوجهة',
  pickupDate: 'تاريخ المشوار',
  flightDate: 'تاريخ الرحلة',
  pickupTime: 'وقت الانطلاق',
  timePicker: {
    timeFormat: 'تنسيق الوقت', twelveHour: '12 ساعة', twentyFourHour: '24 ساعة', period: 'صباحًا أو مساءً',
    hour: 'الساعة', minute: 'الدقائق', editHour: 'اختر الساعة', editMinute: 'اختر الدقائق',
    selectHour: 'اختر الساعة · يمكنك استخدام مفاتيح الأسهم', selectMinute: 'اختر الدقائق · يمكنك استخدام مفاتيح الأسهم',
    selectedHour: (value: number, period?: string) => `الساعة المختارة ${value}${period ? ` ${period}` : ''}`,
    selectedMinute: (value: number) => `الدقيقة المختارة ${value}`,
  },
  flightNumber: 'رقم الرحلة',
  flightExample: 'مثال PK-753',
  from: 'من',
  to: 'إلى',
  flightRoutePreview: 'معاينة مسار الرحلة',
  selectDuration: 'اختر المدة',
  hours: 'ساعات',
  included: 'مشمولة',
  needMore: 'تحتاج أكثر من ساعتين؟',
  chooseDayOption: 'اختر نصف يوم أو يوم كامل',
  bookingDuration: 'مدة الحجز',
  halfDay: 'نصف يوم',
  fullDay: 'يوم كامل',
  upTo4Hours: 'إلى ٤ ساعات',
  upTo10Hours: 'إلى ١٠ ساعات',
  bookingQuestion: 'الحجز لك أو لضيف؟',
  forMyself: 'لي',
  selfTravel: 'أنا اللي بسافر',
  forGuest: 'لضيف',
  guestTravel: 'شخص ثاني هو اللي بيسافر',
  yourDetails: 'بياناتك',
  enterYourDetails: 'دخل بيانات التواصل الخاصة بك.',
  guestDetails: 'بيانات الضيف',
  enterGuestDetails: 'دخل بيانات الضيف',
  fullName: 'الاسم الكامل',
  namePlaceholder: 'الاسم',
  guestName: 'اسم الضيف',
  phoneNumber: 'رقم الجوال',
  emailAddress: 'البريد الإلكتروني',
  back: 'رجوع',
  continue: 'كمّل',
  km: 'كم',
  validation: {
    required: 'هذا الحقل مطلوب.',
    email: 'دخل بريد إلكتروني صحيح.',
    phone: 'دخل ٨ أرقام على الأقل.',
    characters: (count: number) => `دخل ${count} أحرف على الأقل.`,
    cardNumber: 'رقم البطاقة يجب أن يحتوي على ١٦ رقمًا.',
    cardName: 'دخل حرفين على الأقل.',
    expiry: 'استخدم الصيغة MM/YY.',
    cvv: 'دخل ٣ أو ٤ أرقام.',
  },
  calendar: {
    locale: 'ar-SA-u-ca-gregory',
    monthLocale: 'ar-SA-u-ca-gregory',
    weekdays: ['اث', 'ثل', 'أر', 'خم', 'جم', 'سب', 'أح'],
    label: 'التقويم',
  },
  airports: [
    'مطار الملك خالد الدولي (RUH)',
    'مطار الملك عبدالعزيز الدولي (JED)',
    'مطار الملك فهد الدولي (DMM)',
    'مطار الأمير محمد بن عبدالعزيز الدولي (MED)',
  ],
  locations: ['الرياض', 'جدة', 'الدمام', 'مكة', 'المدينة', 'الخبر', 'تبوك', 'حائل', 'أبها', 'ينبع', 'الطائف', 'جيزان', 'العُلا', 'نجران', 'الباحة'],
  selectRide: 'اختر سيارتك',
  selectRideSubtitle: 'اختر السيارة اللي تناسبك وكمل بيانات الركاب.',
  chooseCategory: 'اختر الفئة اللي تناسب مشوارك.',
  categories: [
    { name: 'الفئة الأولى', copy: 'تنقّل راقٍ ومريح للمشاوير اليومية والقصيرة.' },
    { name: 'فئة الأعمال', copy: 'سيدان فاخرة بمساحة أوسع ومناسبة للأعمال.' },
    { name: 'فان', copy: 'سيارات عائلية مع سائق للمجموعات والعفش.' },
    { name: 'سيدان', copy: 'سيدان فاخرة بمقاعد جلد وخصوصية عالية.' },
    { name: 'دفع رباعي', copy: 'سيارات واسعة للمجموعات والعفش.' },
  ],
  availableVehicles: (category: string) => `السيارات المتاحة من فئة ${category}.`,
  passengersAndBags: 'راكبين و٤ شنط',
  reviewBooking: 'راجع حجزك',
  pickup: 'الانطلاق',
  summaryDestination: 'الوجهة',
  summaryDropOff: 'التوصيل',
  summaryLabels: {
    flight: 'الرحلة', flightDate: 'تاريخ الرحلة', pickupDate: 'تاريخ المشوار', pickupTime: 'وقت الانطلاق',
    duration: 'المدة', journey: 'نوع المشوار', category: 'الفئة', vehicle: 'السيارة',
  },
  summaryValues: { city: 'رحلة المدن', oneWay: 'اتجاه واحد' },
  addresses: {
    kingFahd: 'طريق الملك فهد، الرياض', riyadhFront: 'واجهة الرياض، الرياض',
    riyadh: 'الرياض، السعودية', jeddah: 'جدة، السعودية', airport: 'مطار الملك خالد الدولي، RUH',
  },
  fareSummary: 'ملخص السعر',
  fareSubtitle: {
    airport: 'هذا سعر توصيلة المطار.', hourly: 'هذا سعر حجز السائق بالساعة.',
    city: 'هذا سعر رحلة المدن.', day: 'هذا سعر الخدمة اليومية.', oneWay: 'هذا سعر المشوار باتجاه واحد.',
  },
  fareLabels: {
    airport: 'سعر التوصيلة', hourly: 'سعر الحجز بالساعة', city: 'سعر الرحلة', day: 'سعر الخدمة اليومية', oneWay: 'سعر المشوار',
  },
  serviceFee: 'رسوم الخدمة',
  airportService: 'خدمة المطار',
  vat: 'ضريبة القيمة المضافة (١٥٪)',
  totalFare: 'الإجمالي',
  paymentMethod: 'طريقة الدفع',
  cardNumber: 'رقم البطاقة',
  cardName: 'الاسم على البطاقة',
  cardNamePlaceholder: 'سلطان علي',
  expiryDate: 'تاريخ الانتهاء',
  cvv: 'رمز الأمان',
  secureVerification: 'تحقق آمن',
  otpTitle: 'دخل رمز التحقق اللي أرسلناه لجوالك.',
  otpSent: 'أرسلنا لك رمز تحقق من ٦ أرقام.',
  otpDigit: (digit: number) => `رقم التحقق ${digit}`,
  otpResend: 'ما وصلك الرمز؟ تقدر تعيد الإرسال بعد 00:45',
  resendOtp: 'أعد إرسال الرمز',
  contactDetails: 'بياناتك للتواصل',
  yourName: 'الاسم الكامل',
  yourEmail: 'البريد الإلكتروني',
  yourPhone: 'رقم الجوال',
  baseFare: 'السعر الأساسي',
  requestReceived: 'تم استلام الطلب',
  receivedTitle: 'استلمنا طلب حجزك.',
  receivedBody: 'تفاصيل حجزك وتأكيده راح يوصلك على بريدك الإلكتروني.',
  bookingReference: 'رقم الحجز',
  trackJourney: 'التطبيق قريباً',
  trackBody: 'تطبيق وايت لاين قادم قريباً.',
  downloadOn: 'حمّل من',
  getItOn: 'متوفر على',
  downloadApp: 'تم',
  mobileAppAlt: 'تطبيق وايت لاين للجوال',
  closeLabel: 'إغلاق نافذة الحجز',
  cancelTitle: 'تريد تلغي الحجز؟',
  cancelBody: 'راح تنحذف كل البيانات اللي دخلتها. متأكد تبي تغادر؟',
  cancelKeepBooking: 'كمّل الحجز',
  cancelYes: 'نعم، إلغاء',
}

export type BookingDialogCopy = typeof en
export const bookingDialogCopy: Record<LangCode, BookingDialogCopy> = { en, ar }
