import type { LangCode } from './i18n'

const en = {
  services: {
    airport: 'Airport Transfer',
    hourly: 'Hourly Chauffeur',
    city: 'City-to-City',
    day: 'Day Service',
    oneWay: 'One Way Ride',
  },
  dialogLabel: 'booking',
  tripDetails: 'Trip Details',
  tripSubtitle: 'Tell us where and when you need your ride.',
  pickupAirport: 'Pickup Airport',
  selectAirport: 'Select Airport',
  pickupLocation: 'Pickup Location',
  selectPickup: 'Select pickup location',
  destination: 'Destination',
  dropOff: 'Drop-off Location',
  optionalDropOff: 'Drop-off Location (Optional)',
  selectDropOff: 'Select drop-off location',
  enterDestination: 'Enter destination',
  pickupDate: 'Pickup Date',
  flightDate: 'Flight Date',
  pickupTime: 'Pickup Time',
  flightNumber: 'Flight Number',
  flightExample: '✈  e.g. PK-753',
  from: 'From',
  to: 'To',
  flightRoutePreview: 'Flight route preview',
  selectDuration: 'Select Duration',
  hours: 'hours',
  included: 'included',
  needMore: 'Need more than 2 hours?',
  chooseDayOption: 'Choose Half Day or Full Day options',
  bookingDuration: 'Booking Duration',
  halfDay: 'Half Day',
  fullDay: 'Full Day',
  upTo4Hours: 'Up to 4 hours',
  upTo10Hours: 'Up to 10 hours',
  bookingQuestion: 'Are you making this booking for yourself or a guest?',
  forMyself: 'For Myself',
  selfTravel: "I'll be travelling",
  forGuest: 'For a Guest',
  guestTravel: 'Someone else will be travelling',
  guestDetails: 'Guest Details',
  enterGuestDetails: "Please enter your guest's details",
  fullName: 'Full Name',
  guestName: 'Guest name',
  phoneNumber: 'Phone Number',
  emailAddress: 'Email Address',
  back: 'Back',
  continue: 'Continue',
  km: 'km',
  validation: {
    email: 'Enter a valid email address.',
    phone: 'Enter at least 8 digits.',
    characters: (count: number) => `Enter at least ${count} characters.`,
    cardNumber: 'Card number must contain 16 digits.',
    cardName: 'Enter at least 2 characters.',
    expiry: 'Use MM/YY format.',
    cvv: 'Enter 3 or 4 digits.',
  },
  calendar: {
    locale: 'en-GB',
    monthLocale: 'en-US',
    weekdays: ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'],
    label: 'calendar',
  },
  airports: [
    'King Khalid International Airport (RUH)',
    'King Abdulaziz International Airport (JED)',
    'King Fahd International Airport (DMM)',
    'Prince Mohammad bin Abdulaziz International Airport (MED)',
    'Abha International Airport (AHB)',
    'Taif Regional Airport (TIF)',
    'Tabuk Regional Airport (TUU)',
    'Hail Regional Airport (HAS)',
    'Qassim Airport (ELQ)',
    'Yanbu Airport (YNB)',
    'Al-Ula International Airport (ULH)',
    'Jizan Regional Airport (GIZ)',
    'Najran Airport (EAM)',
    'Al Baha Airport (ABT)',
    'Arar Domestic Airport (RAE)',
    'Gurayat Domestic Airport (URY)',
    'Wadi ad-Dawasir Airport (WAE)',
    'Al-Jawf Domestic Airport (AJF)',
    'Sharurah Airport (SHW)',
    'Rafha Domestic Airport (RAH)',
  ],
  locations: ['Riyadh', 'Jeddah', 'Dammam', 'Makkah', 'Madinah', 'Al Khobar', 'Tabuk', 'Hail', 'Abha', 'Yanbu', 'Taif', 'Jizan', 'Al-Ula', 'Najran', 'Al Baha'],
  selectRide: 'Select Your Ride',
  selectRideSubtitle: 'Choose your preferred vehicle and provide passenger details.',
  chooseCategory: 'Choose the category that best fits your journey.',
  categories: [
    { name: 'First Class', copy: 'Efficient transportation for daily commutes and short city trips.' },
    { name: 'Business Class', copy: 'Premium sedans with extra legroom, tailored for business.' },
    { name: 'Van', copy: 'Chauffeur-driven MPVs for groups with ample luggage.' },
    { name: 'Sedan', copy: 'Luxury sedans featuring leather privacy glass.' },
    { name: 'SUV', copy: 'Chauffeur-driven SUVs for groups with ample luggage.' },
  ],
  availableVehicles: (category: string) => `Available ${category} vehicles.`,
  passengersAndBags: '2 passengers and 4 bags',
  reviewBooking: 'Review Your Booking',
  pickup: 'Pickup',
  summaryDestination: 'Destination',
  summaryDropOff: 'Drop Off',
  summaryLabels: {
    flight: 'Flight', flightDate: 'Flight Date', pickupDate: 'Pickup Date', pickupTime: 'Pickup Time',
    duration: 'Duration', journey: 'Journey', category: 'Category', vehicle: 'Vehicle',
  },
  summaryValues: { city: 'City-to-City', oneWay: 'One Way' },
  addresses: {
    kingFahd: 'King Fahd Road, Riyadh', riyadhFront: 'Riyadh Front, Riyadh',
    riyadh: 'Riyadh, Saudi Arabia', jeddah: 'Jeddah, Saudi Arabia', airport: 'Riyadh International Airport, RUH',
  },
  fareSummary: 'Fare Summary',
  fareSubtitle: {
    airport: 'Your fare for this airport transfer.', hourly: 'Your fare for this hourly booking.',
    city: 'Your fare for this city-to-city journey.', day: 'Your fare for this day service.', oneWay: 'Your fare for this one-way ride.',
  },
  fareLabels: {
    airport: 'Transfer Fare', hourly: 'Hourly Fare', city: 'Journey Fare', day: 'Day Service Fare', oneWay: 'Ride Fare',
  },
  serviceFee: 'Service Fee',
  airportService: 'Airport Service',
  vat: 'VAT (15%)',
  totalFare: 'Total Fare',
  paymentMethod: 'Payment Method',
  cardNumber: 'Card Number',
  cardName: 'Name on Card',
  cardNamePlaceholder: 'Sultan Ali',
  expiryDate: 'Expiry Date',
  cvv: 'CVV',
  secureVerification: 'Secure verification',
  otpTitle: 'Enter the one-time password sent to your phone.',
  otpSent: "We've sent a 6-digit verification code.",
  otpDigit: (digit: number) => `OTP digit ${digit}`,
  otpResend: "Didn't get the code? Resend in 00:45",
  resendOtp: 'Resend OTP',
  requestReceived: 'Request Received',
  receivedTitle: "We've received your booking request.",
  receivedBody: 'Our team will find the best chauffeur for your journey and assign one to your booking.',
  bookingReference: 'Booking Reference',
  trackJourney: 'Track Your Journey In The Mobile App',
  trackBody: 'For live chauffeur and vehicle tracking, download the WhiteLine app.',
  downloadOn: 'Download on the',
  getItOn: 'Get it on',
  downloadApp: 'Download App',
  mobileAppAlt: 'White Line mobile app',
}

const ar: typeof en = {
  services: {
    airport: 'توصيل المطار',
    hourly: 'سائق بالساعة',
    city: 'من مدينة لمدينة',
    day: 'خدمة يومية',
    oneWay: 'مشوار باتجاه واحد',
  },
  dialogLabel: 'حجز',
  tripDetails: 'تفاصيل المشوار',
  tripSubtitle: 'علّمنا من وين ومتى تبي مشوارك.',
  pickupAirport: 'مطار الاستقبال',
  selectAirport: 'اختر المطار',
  pickupLocation: 'موقع الانطلاق',
  selectPickup: 'اختر موقع الانطلاق',
  destination: 'الوجهة',
  dropOff: 'موقع التوصيل',
  optionalDropOff: 'موقع التوصيل (اختياري)',
  selectDropOff: 'اختر موقع التوصيل',
  enterDestination: 'اكتب الوجهة',
  pickupDate: 'تاريخ المشوار',
  flightDate: 'تاريخ الرحلة',
  pickupTime: 'وقت الانطلاق',
  flightNumber: 'رقم الرحلة',
  flightExample: '✈  مثال PK-753',
  from: 'من',
  to: 'إلى',
  flightRoutePreview: 'معاينة مسار الرحلة',
  selectDuration: 'اختر المدة',
  hours: 'ساعات',
  included: 'مشمولة',
  needMore: 'تحتاج أكثر من ساعتين؟',
  chooseDayOption: 'اختر نصف يوم أو يوم كامل',
  bookingDuration: 'مدة الحجز',
  halfDay: 'نصف يوم',
  fullDay: 'يوم كامل',
  upTo4Hours: 'إلى ٤ ساعات',
  upTo10Hours: 'إلى ١٠ ساعات',
  bookingQuestion: 'الحجز لك أو لضيف؟',
  forMyself: 'لي',
  selfTravel: 'أنا اللي بسافر',
  forGuest: 'لضيف',
  guestTravel: 'شخص ثاني هو اللي بيسافر',
  guestDetails: 'بيانات الضيف',
  enterGuestDetails: 'دخل بيانات الضيف',
  fullName: 'الاسم الكامل',
  guestName: 'اسم الضيف',
  phoneNumber: 'رقم الجوال',
  emailAddress: 'البريد الإلكتروني',
  back: 'رجوع',
  continue: 'كمّل',
  km: 'كم',
  validation: {
    email: 'دخل بريد إلكتروني صحيح.',
    phone: 'دخل ٨ أرقام على الأقل.',
    characters: (count: number) => `دخل ${count} أحرف على الأقل.`,
    cardNumber: 'رقم البطاقة يجب أن يحتوي على ١٦ رقمًا.',
    cardName: 'دخل حرفين على الأقل.',
    expiry: 'استخدم الصيغة MM/YY.',
    cvv: 'دخل ٣ أو ٤ أرقام.',
  },
  calendar: {
    locale: 'ar-SA-u-ca-gregory',
    monthLocale: 'ar-SA-u-ca-gregory',
    weekdays: ['اث', 'ثل', 'أر', 'خم', 'جم', 'سب', 'أح'],
    label: 'التقويم',
  },
  airports: [
    'مطار الملك خالد الدولي (RUH)',
    'مطار الملك عبدالعزيز الدولي (JED)',
    'مطار الملك فهد الدولي (DMM)',
    'مطار الأمير محمد بن عبدالعزيز الدولي (MED)',
    'مطار أبها الدولي (AHB)',
    'مطار الطائف الإقليمي (TIF)',
    'مطار تبوك الإقليمي (TUU)',
    'مطار حائل الإقليمي (HAS)',
    'مطار القصيم (ELQ)',
    'مطار ينبع (YNB)',
    'مطار العُلا الدولي (ULH)',
    'مطار جيزان الإقليمي (GIZ)',
    'مطار نجران (EAM)',
    'مطار الباحة (ABT)',
    'مطار عرعر المحلي (RAE)',
    'مطار القريات المحلي (URY)',
    'مطار وادي الدواسر (WAE)',
    'مطار الجوف المحلي (AJF)',
    'مطار شرورة (SHW)',
    'مطار رفحاء المحلي (RAH)',
  ],
  locations: ['الرياض', 'جدة', 'الدمام', 'مكة', 'المدينة', 'الخبر', 'تبوك', 'حائل', 'أبها', 'ينبع', 'الطائف', 'جيزان', 'العُلا', 'نجران', 'الباحة'],
  selectRide: 'اختر سيارتك',
  selectRideSubtitle: 'اختر السيارة اللي تناسبك وكمل بيانات الركاب.',
  chooseCategory: 'اختر الفئة اللي تناسب مشوارك.',
  categories: [
    { name: 'الفئة الأولى', copy: 'تنقّل راقٍ ومريح للمشاوير اليومية والقصيرة.' },
    { name: 'فئة الأعمال', copy: 'سيدان فاخرة بمساحة أوسع ومناسبة للأعمال.' },
    { name: 'فان', copy: 'سيارات عائلية مع سائق للمجموعات والعفش.' },
    { name: 'سيدان', copy: 'سيدان فاخرة بمقاعد جلد وخصوصية عالية.' },
    { name: 'دفع رباعي', copy: 'سيارات واسعة للمجموعات والعفش.' },
  ],
  availableVehicles: (category: string) => `السيارات المتاحة من فئة ${category}.`,
  passengersAndBags: 'راكبين و٤ شنط',
  reviewBooking: 'راجع حجزك',
  pickup: 'الانطلاق',
  summaryDestination: 'الوجهة',
  summaryDropOff: 'التوصيل',
  summaryLabels: {
    flight: 'الرحلة', flightDate: 'تاريخ الرحلة', pickupDate: 'تاريخ المشوار', pickupTime: 'وقت الانطلاق',
    duration: 'المدة', journey: 'نوع المشوار', category: 'الفئة', vehicle: 'السيارة',
  },
  summaryValues: { city: 'من مدينة لمدينة', oneWay: 'اتجاه واحد' },
  addresses: {
    kingFahd: 'طريق الملك فهد، الرياض', riyadhFront: 'واجهة الرياض، الرياض',
    riyadh: 'الرياض، السعودية', jeddah: 'جدة، السعودية', airport: 'مطار الملك خالد الدولي، RUH',
  },
  fareSummary: 'ملخص السعر',
  fareSubtitle: {
    airport: 'هذا سعر توصيلة المطار.', hourly: 'هذا سعر حجز السائق بالساعة.',
    city: 'هذا سعر مشوارك بين المدن.', day: 'هذا سعر الخدمة اليومية.', oneWay: 'هذا سعر المشوار باتجاه واحد.',
  },
  fareLabels: {
    airport: 'سعر التوصيلة', hourly: 'سعر الحجز بالساعة', city: 'سعر الرحلة', day: 'سعر الخدمة اليومية', oneWay: 'سعر المشوار',
  },
  serviceFee: 'رسوم الخدمة',
  airportService: 'خدمة المطار',
  vat: 'ضريبة القيمة المضافة (١٥٪)',
  totalFare: 'الإجمالي',
  paymentMethod: 'طريقة الدفع',
  cardNumber: 'رقم البطاقة',
  cardName: 'الاسم على البطاقة',
  cardNamePlaceholder: 'سلطان علي',
  expiryDate: 'تاريخ الانتهاء',
  cvv: 'رمز الأمان',
  secureVerification: 'تحقق آمن',
  otpTitle: 'دخل رمز التحقق اللي أرسلناه لجوالك.',
  otpSent: 'أرسلنا لك رمز تحقق من ٦ أرقام.',
  otpDigit: (digit: number) => `رقم التحقق ${digit}`,
  otpResend: 'ما وصلك الرمز؟ تقدر تعيد الإرسال بعد 00:45',
  resendOtp: 'أعد إرسال الرمز',
  requestReceived: 'تم استلام الطلب',
  receivedTitle: 'استلمنا طلب حجزك.',
  receivedBody: 'فريقنا بيختار لك أنسب سائق للمشوار ويضيفه لحجزك.',
  bookingReference: 'رقم الحجز',
  trackJourney: 'تابع مشوارك من التطبيق',
  trackBody: 'حمّل تطبيق وايت لاين وتابع السائق والسيارة مباشرة.',
  downloadOn: 'حمّل من',
  getItOn: 'متوفر على',
  downloadApp: 'حمّل التطبيق',
  mobileAppAlt: 'تطبيق وايت لاين للجوال',
}

export type BookingDialogCopy = typeof en
export const bookingDialogCopy: Record<LangCode, BookingDialogCopy> = { en, ar }
