import type { LangCode } from './i18n'

const en = {
  services: {
    airport: 'Airport Transfer',
    hourly: 'Hourly Chauffeur',
    city: 'City Trip',
    day: 'Day Service',
    oneWay: 'One Way Ride',
  },
  dialogLabel: 'booking',
  tripDetails: 'Trip Details',
  tripSubtitle: 'Tell us where and when you need your ride.',
  arrival: 'Arrival',
  departure: 'Departure',
  pickupAirport: 'Pickup Airport',
  dropOffAirport: 'Drop-off Airport',
  selectAirport: 'Select Airport',
  pickupLocation: 'Pickup Location',
  selectPickup: 'Select pickup location',
  destination: 'Destination',
  dropOff: 'Destination',
  optionalDropOff: 'Drop-off Location (Optional)',
  selectDropOff: 'Select drop-off location',
  enterDestination: 'Enter destination',
  pickupDate: 'Pickup Date',
  flightDate: 'Flight Date',
  pickupTime: 'Pickup Time',
  timePicker: {
    timeFormat: 'Time format', twelveHour: '12 hour', twentyFourHour: '24 hour', period: 'AM or PM',
    hour: 'Hour', minute: 'Minute', editHour: 'Choose hour', editMinute: 'Choose minutes',
    selectHour: 'Select hour · Arrow keys also work', selectMinute: 'Select minutes · Arrow keys also work',
    selectedHour: (value: number, period?: string) => `Selected hour ${value}${period ? ` ${period}` : ''}`,
    selectedMinute: (value: number) => `Selected minute ${value}`,
  },
  flightNumber: 'Flight Number',
  flightExample: 'e.g. PK-753',
  from: 'From',
  to: 'To',
  flightRoutePreview: 'Flight route preview',
  selectDuration: 'Duration',
  hours: 'hours',
  included: 'included',
  needMore: 'Need more than 2 hours?',
  chooseDayOption: 'Choose Half Day or Full Day options',
  bookingDuration: 'Booking Duration',
  halfDay: 'Half Day',
  fullDay: 'Full Day',
  upTo4Hours: 'Up to 4 hours',
  upTo10Hours: 'Up to 8 hours',
  bookingQuestion: 'Are you making this booking for yourself or a guest?',
  forMyself: 'For Myself',
  selfTravel: "I'll be travelling",
  forGuest: 'For a Guest',
  guestTravel: 'Someone else will be travelling',
  yourDetails: 'Your Details',
  enterYourDetails: 'Please enter your contact details.',
  guestDetails: 'Guest Details',
  enterGuestDetails: "Please enter your guest's details",
  fullName: 'Full Name',
  namePlaceholder: 'Name',
  guestName: 'Guest name',
  phoneNumber: 'Phone Number',
  emailAddress: 'Email Address',
  back: 'Back',
  continue: 'Continue',
  km: 'km',
  validation: {
    required: 'This field is required.',
    email: 'Enter a valid email address.',
    phone: 'Enter at least 8 digits.',
    characters: (count: number) => `Enter at least ${count} characters.`,
    cardNumber: 'Card number must contain 16 digits.',
    cardName: 'Enter at least 2 characters.',
    expiry: 'Use MM/YY format.',
    cvv: 'Enter 3 or 4 digits.',
  },
  calendar: {
    locale: 'en-GB',
    monthLocale: 'en-US',
    weekdays: ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'],
    label: 'calendar',
  },
  airports: [
    'King Khalid International Airport (RUH)',
    'King Abdulaziz International Airport (JED)',
    'King Fahd International Airport (DMM)',
    'Prince Mohammad bin Abdulaziz International Airport (MED)',
  ],
  locations: ['Riyadh', 'Jeddah', 'Dammam', 'Makkah', 'Madinah', 'Al Khobar', 'Tabuk', 'Hail', 'Abha', 'Yanbu', 'Taif', 'Jizan', 'Al-Ula', 'Najran', 'Al Baha'],
  selectRide: 'Select Your Ride',
  selectRideSubtitle: 'Choose the vehicle class and car that best fit your journey.',
  chooseCategory: 'Choose the category that best fits your journey.',
  categoryDotLabel: (index: number) => `Go to vehicle class ${index}`,
  vehicleDotLabel: (index: number) => `Go to vehicle ${index}`,
  categories: [
    { name: 'First Class', copy: 'Efficient transportation for daily commutes and short city trips.' },
    { name: 'Business Class', copy: 'Premium sedans with extra legroom, tailored for business.' },
    { name: 'Van', copy: 'Chauffeur-driven MPVs for groups with ample luggage.' },
    { name: 'Sedan', copy: 'Luxury sedans featuring leather privacy glass.' },
    { name: 'SUV', copy: 'Chauffeur-driven SUVs for groups with ample luggage.' },
  ],
  availableVehicles: (category: string) => `Available ${category} vehicles.`,
  passengersAndBags: '2 passengers and 4 bags',
  fareFrom: 'From',
  farePerKm: (amount: string) => `+ ${amount}/km`,
  farePerHour: 'per hour',
  fareHalfDay: 'half day',
  fareFullDay: 'full day',
  reviewBooking: 'Review Your Booking',
  reviewSubtitle: 'Confirm your route, schedule, passenger details, and selected vehicle before we calculate the fare.',
  pickup: 'Pickup',
  summaryDestination: 'Destination',
  summaryDropOff: 'Drop Off',
  summaryLabels: {
    flight: 'Flight', flightDate: 'Flight Date', pickupDate: 'Pickup Date', pickupTime: 'Pickup Time',
    duration: 'Duration', journey: 'Journey', category: 'Category', vehicle: 'Vehicle',
  },
  summaryValues: { city: 'City Trip', oneWay: 'One Way' },
  addresses: {
    kingFahd: 'King Fahd Road, Riyadh', riyadhFront: 'Riyadh Front, Riyadh',
    riyadh: 'Riyadh, Saudi Arabia', jeddah: 'Jeddah, Saudi Arabia', airport: 'Riyadh International Airport, RUH',
  },
  fareSummary: 'Fare Summary',
  fareSubtitle: {
    airport: 'Your fare for this airport transfer.', hourly: 'Your fare for this hourly booking.',
    city: 'Your fare for this City Trip.', day: 'Your fare for this day service.', oneWay: 'Your fare for this one-way ride.',
  },
  fareLabels: {
    airport: 'Transfer Fare', hourly: 'Hourly Fare', city: 'Journey Fare', day: 'Day Service Fare', oneWay: 'Ride Fare',
  },
  serviceFee: 'Service Fee',
  distanceFare: 'Distance Fare',
  subtotal: 'Subtotal',
  airportService: 'Airport Service',
  vat: 'VAT (15%)',
  totalFare: 'Total Fare',
  fareLoading: 'Calculating fare…',
  fareError: 'Unable to calculate fare. Please try again later.',
  fareApiErrors: {
    city_to_city_riyadh: 'City-to-city trips can only be booked from Riyadh. Please update your pickup location.',
  } as Record<string, string>,
  bookingSubmitError: 'Something went wrong. Please try again later.',
  bookingAuthError: 'Your session has expired. Please sign in again to continue.',
  bookingAuthErrorAction: 'Sign in again',
  submitting: 'Submitting…',
  confirmBooking: 'Confirm Booking',
  fareDistance: (km: number) => `${km.toFixed(1)} km`,
  fareDuration: (min: number) => `~${min} min`,
  paymentMethod: 'Payment Method',
  cardNumber: 'Card Number',
  cardName: 'Name on Card',
  cardNamePlaceholder: 'Sultan Ali',
  expiryDate: 'Expiry Date',
  cvv: 'CVV',
  secureVerification: 'Secure verification',
  otpTitle: 'Enter the one-time password sent to your phone.',
  otpSent: "We've sent a 4-digit verification code.",
  otpDigit: (digit: number) => `OTP digit ${digit}`,
  otpResend: "Didn't get the code? Resend in 00:45",
  resendOtp: 'Resend OTP',
  otpSentToast: (phone: string) => `OTP sent to ${phone}`,
  customerLoginTitle: 'Sign in to continue',
  customerLoginBody: 'Enter your phone number and we will send a one-time password.',
  sendOtp: 'Send OTP',
  sendingOtp: 'Sending...',
  ksaPhoneRequired: 'Enter a Saudi mobile number in +966XXXXXXXXX format.',
  verifyOtp: 'Verify OTP',
  verifyingOtp: 'Verifying...',
  loadingProfile: 'Loading your profile...',
  signInAgain: 'Sign in again',
  completeProfileTitle: 'Complete your profile',
  completeProfileBody: 'Add the missing contact details to continue your booking.',
  completeProfile: 'Complete Profile',
  savingProfile: 'Saving...',
  otpSendError: 'Could not send the OTP. Please try again.',
  otpVerifyError: 'Could not verify the OTP. Please check the code and try again.',
  profileCompleteError: 'Could not complete your profile. Please try again.',
  contactDetails: 'Your Contact Details',
  yourName: 'Full Name',
  yourEmail: 'Email Address',
  yourPhone: 'Phone Number',
  baseFare: 'Base Fare',
  requestReceived: 'Booking Requested!',
  successSubtitle: 'Your ride request has been submitted successfully.',
  receivedTitle: "We've received your request!",
  receivedBody: 'Our team will review your booking and send a confirmation to your email shortly.',
  bookingReference: 'Booking Reference',
  trackJourney: 'App Coming Soon',
  trackBody: 'The White Line app is coming soon.',
  downloadOn: 'Download on the',
  getItOn: 'Get it on',
  downloadApp: 'Done',
  mobileAppAlt: 'White Line mobile app',
  closeLabel: 'Close booking dialog',
  cancelTitle: 'Cancel your booking?',
  cancelBody: "All the information you've entered will be lost. Are you sure you want to leave?",
  cancelKeepBooking: 'Continue Booking',
  cancelYes: 'Yes, Cancel',
  redirectingTitle: 'Redirecting to Payment',
  redirectingBody: 'You are being securely redirected to the payment page. Please do not close this window.',
  flightLookupLoading: 'Looking up flight…',
  flightLookupDateNeeded: 'Enter the flight date to look up your flight.',
  flightLookupNotFound: (num: string) => `No flight found for ${num} on that date.`,
  flightLookupUnavailable: 'Flight data is temporarily unavailable. Please try again.',
  flightLookupValidationError: 'Enter a valid IATA flight number (e.g. SV123, EK505).',
  flightLookupNetworkError: 'Network error. Check your connection and try again.',
  flightAutoFillTitle: 'Auto-fill from flight data?',
  flightAutoFillBody: "We've found your flight. Next, choose your preferred pickup time after arrival.",
  flightAutoFillConfirm: 'Apply',
  pickupEstimatorTitle: 'For estimation of pick up, kindly select the time for driver to appear after arrival',
  pickupEstimatorByMinutes: 'By minutes',
  pickupEstimatorByTime: 'By time',
  pickupEstimatorAfterArrival: (min: number) => `${min} minutes after arrival`,
  pickupEstimatorConfirm: 'Set Pickup Time',
  pickupEstimatorBack: 'Back',
}

const ar: typeof en = {
  services: {
    airport: 'توصيل المطار',
    hourly: 'سائق بالساعة',
    city: 'رحلة المدن',
    day: 'خدمة يومية',
    oneWay: 'مشوار باتجاه واحد',
  },
  dialogLabel: 'حجز',
  tripDetails: 'تفاصيل المشوار',
  tripSubtitle: 'علّمنا من وين ومتى تبي مشوارك.',
  arrival: 'وصول',
  departure: 'مغادرة',
  pickupAirport: 'مطار الاستقبال',
  dropOffAirport: 'مطار التوصيل',
  selectAirport: 'اختر المطار',
  pickupLocation: 'موقع الانطلاق',
  selectPickup: 'اختر موقع الانطلاق',
  destination: 'الوجهة',
  dropOff: 'الوجهة',
  optionalDropOff: 'موقع التوصيل (اختياري)',
  selectDropOff: 'اختر موقع التوصيل',
  enterDestination: 'اكتب الوجهة',
  pickupDate: 'تاريخ المشوار',
  flightDate: 'تاريخ الرحلة',
  pickupTime: 'وقت الانطلاق',
  timePicker: {
    timeFormat: 'تنسيق الوقت', twelveHour: '12 ساعة', twentyFourHour: '24 ساعة', period: 'صباحًا أو مساءً',
    hour: 'الساعة', minute: 'الدقائق', editHour: 'اختر الساعة', editMinute: 'اختر الدقائق',
    selectHour: 'اختر الساعة · يمكنك استخدام مفاتيح الأسهم', selectMinute: 'اختر الدقائق · يمكنك استخدام مفاتيح الأسهم',
    selectedHour: (value: number, period?: string) => `الساعة المختارة ${value}${period ? ` ${period}` : ''}`,
    selectedMinute: (value: number) => `الدقيقة المختارة ${value}`,
  },
  flightNumber: 'رقم الرحلة',
  flightExample: 'مثال PK-753',
  from: 'من',
  to: 'إلى',
  flightRoutePreview: 'معاينة مسار الرحلة',
  selectDuration: 'المدة',
  hours: 'ساعات',
  included: 'مشمولة',
  needMore: 'تحتاج أكثر من ساعتين؟',
  chooseDayOption: 'اختر نصف يوم أو يوم كامل',
  bookingDuration: 'مدة الحجز',
  halfDay: 'نصف يوم',
  fullDay: 'يوم كامل',
  upTo4Hours: 'إلى ٤ ساعات',
  upTo10Hours: 'إلى ٨ ساعات',
  bookingQuestion: 'الحجز لك أو لضيف؟',
  forMyself: 'لي',
  selfTravel: 'أنا اللي بسافر',
  forGuest: 'لضيف',
  guestTravel: 'شخص ثاني هو اللي بيسافر',
  yourDetails: 'بياناتك',
  enterYourDetails: 'دخل بيانات التواصل الخاصة بك.',
  guestDetails: 'بيانات الضيف',
  enterGuestDetails: 'دخل بيانات الضيف',
  fullName: 'الاسم الكامل',
  namePlaceholder: 'الاسم',
  guestName: 'اسم الضيف',
  phoneNumber: 'رقم الجوال',
  emailAddress: 'البريد الإلكتروني',
  back: 'رجوع',
  continue: 'كمّل',
  km: 'كم',
  validation: {
    required: 'هذا الحقل مطلوب.',
    email: 'دخل بريد إلكتروني صحيح.',
    phone: 'دخل ٨ أرقام على الأقل.',
    characters: (count: number) => `دخل ${count} أحرف على الأقل.`,
    cardNumber: 'رقم البطاقة يجب أن يحتوي على ١٦ رقمًا.',
    cardName: 'دخل حرفين على الأقل.',
    expiry: 'استخدم الصيغة MM/YY.',
    cvv: 'دخل ٣ أو ٤ أرقام.',
  },
  calendar: {
    locale: 'ar-SA-u-ca-gregory',
    monthLocale: 'ar-SA-u-ca-gregory',
    weekdays: ['اث', 'ثل', 'أر', 'خم', 'جم', 'سب', 'أح'],
    label: 'التقويم',
  },
  airports: [
    'مطار الملك خالد الدولي (RUH)',
    'مطار الملك عبدالعزيز الدولي (JED)',
    'مطار الملك فهد الدولي (DMM)',
    'مطار الأمير محمد بن عبدالعزيز الدولي (MED)',
  ],
  locations: ['الرياض', 'جدة', 'الدمام', 'مكة', 'المدينة', 'الخبر', 'تبوك', 'حائل', 'أبها', 'ينبع', 'الطائف', 'جيزان', 'العُلا', 'نجران', 'الباحة'],
  selectRide: 'اختر سيارتك',
  selectRideSubtitle: 'اختر فئة المركبة والسيارة الأنسب لمشوارك.',
  chooseCategory: 'اختر الفئة اللي تناسب مشوارك.',
  categoryDotLabel: (index: number) => `انتقل إلى فئة المركبة ${index}`,
  vehicleDotLabel: (index: number) => `انتقل إلى السيارة ${index}`,
  categories: [
    { name: 'الفئة الأولى', copy: 'تنقّل راقٍ ومريح للمشاوير اليومية والقصيرة.' },
    { name: 'فئة الأعمال', copy: 'سيدان فاخرة بمساحة أوسع ومناسبة للأعمال.' },
    { name: 'فان', copy: 'سيارات عائلية مع سائق للمجموعات والعفش.' },
    { name: 'سيدان', copy: 'سيدان فاخرة بمقاعد جلد وخصوصية عالية.' },
    { name: 'دفع رباعي', copy: 'سيارات واسعة للمجموعات والعفش.' },
  ],
  availableVehicles: (category: string) => `السيارات المتاحة من فئة ${category}.`,
  passengersAndBags: 'راكبين و٤ شنط',
  fareFrom: 'ابتداءً من',
  farePerKm: (amount: string) => `+ ${amount}/كم`,
  farePerHour: 'لكل ساعة',
  fareHalfDay: 'نصف يوم',
  fareFullDay: 'يوم كامل',
  reviewBooking: 'راجع حجزك',
  reviewSubtitle: 'راجع المسار والوقت وبيانات الركاب والسيارة المختارة قبل حساب السعر.',
  pickup: 'الانطلاق',
  summaryDestination: 'الوجهة',
  summaryDropOff: 'التوصيل',
  summaryLabels: {
    flight: 'الرحلة', flightDate: 'تاريخ الرحلة', pickupDate: 'تاريخ المشوار', pickupTime: 'وقت الانطلاق',
    duration: 'المدة', journey: 'نوع المشوار', category: 'الفئة', vehicle: 'السيارة',
  },
  summaryValues: { city: 'رحلة المدن', oneWay: 'اتجاه واحد' },
  addresses: {
    kingFahd: 'طريق الملك فهد، الرياض', riyadhFront: 'واجهة الرياض، الرياض',
    riyadh: 'الرياض، السعودية', jeddah: 'جدة، السعودية', airport: 'مطار الملك خالد الدولي، RUH',
  },
  fareSummary: 'ملخص السعر',
  fareSubtitle: {
    airport: 'هذا سعر توصيلة المطار.', hourly: 'هذا سعر حجز السائق بالساعة.',
    city: 'هذا سعر رحلة المدن.', day: 'هذا سعر الخدمة اليومية.', oneWay: 'هذا سعر المشوار باتجاه واحد.',
  },
  fareLabels: {
    airport: 'سعر التوصيلة', hourly: 'سعر الحجز بالساعة', city: 'سعر الرحلة', day: 'سعر الخدمة اليومية', oneWay: 'سعر المشوار',
  },
  serviceFee: 'رسوم الخدمة',
  distanceFare: 'سعر المسافة',
  subtotal: 'المجموع قبل الضريبة',
  airportService: 'خدمة المطار',
  vat: 'ضريبة القيمة المضافة (١٥٪)',
  totalFare: 'الإجمالي',
  fareLoading: 'جارٍ حساب السعر…',
  fareError: 'تعذّر حساب السعر. يرجى المحاولة مجدداً لاحقاً.',
  fareApiErrors: {
    city_to_city_riyadh: 'رحلات المدن متاحة فقط انطلاقاً من الرياض. يرجى تغيير موقع الاستلام.',
  } as Record<string, string>,
  bookingSubmitError: 'حدث خطأ ما. يرجى المحاولة مجدداً لاحقاً.',
  bookingAuthError: 'انتهت جلستك. يرجى تسجيل الدخول مجدداً للمتابعة.',
  bookingAuthErrorAction: 'تسجيل الدخول مجدداً',
  submitting: 'جارٍ الإرسال…',
  confirmBooking: 'تأكيد الحجز',
  fareDistance: (km: number) => `${km.toFixed(1)} كم`,
  fareDuration: (min: number) => `~${min} دقيقة`,
  paymentMethod: 'طريقة الدفع',
  cardNumber: 'رقم البطاقة',
  cardName: 'الاسم على البطاقة',
  cardNamePlaceholder: 'سلطان علي',
  expiryDate: 'تاريخ الانتهاء',
  cvv: 'رمز الأمان',
  secureVerification: 'تحقق آمن',
  otpTitle: 'دخل رمز التحقق اللي أرسلناه لجوالك.',
  otpSent: 'أرسلنا لك رمز تحقق من ٤ أرقام.',
  otpDigit: (digit: number) => `رقم التحقق ${digit}`,
  otpResend: 'ما وصلك الرمز؟ تقدر تعيد الإرسال بعد 00:45',
  resendOtp: 'أعد إرسال الرمز',
  otpSentToast: (phone: string) => `تم إرسال الرمز إلى ${phone}`,
  customerLoginTitle: 'سجل الدخول للمتابعة',
  customerLoginBody: 'دخل رقم جوالك ونرسل لك رمز تحقق لمرة واحدة.',
  sendOtp: 'إرسال الرمز',
  sendingOtp: 'جارٍ الإرسال...',
  ksaPhoneRequired: 'دخل رقم جوال سعودي بصيغة +966XXXXXXXXX.',
  verifyOtp: 'تحقق من الرمز',
  verifyingOtp: 'جارٍ التحقق...',
  loadingProfile: 'جارٍ تحميل ملفك...',
  signInAgain: 'سجل الدخول مرة أخرى',
  completeProfileTitle: 'أكمل ملفك',
  completeProfileBody: 'أضف بيانات التواصل الناقصة لإكمال الحجز.',
  completeProfile: 'إكمال الملف',
  savingProfile: 'جارٍ الحفظ...',
  otpSendError: 'تعذّر إرسال رمز التحقق. يرجى المحاولة مجدداً.',
  otpVerifyError: 'تعذّر التحقق من الرمز. تأكد من الرمز وحاول مجدداً.',
  profileCompleteError: 'تعذّر إكمال ملفك. يرجى المحاولة مجدداً.',
  contactDetails: 'بياناتك للتواصل',
  yourName: 'الاسم الكامل',
  yourEmail: 'البريد الإلكتروني',
  yourPhone: 'رقم الجوال',
  baseFare: 'السعر الأساسي',
  requestReceived: 'تم إرسال طلب الحجز!',
  successSubtitle: 'تم إرسال طلب مشوارك بنجاح.',
  receivedTitle: 'استلمنا طلبك!',
  receivedBody: 'فريقنا راح يراجع حجزك وترسل لك رسالة تأكيد على بريدك الإلكتروني قريباً.',
  bookingReference: 'رقم الحجز',
  trackJourney: 'التطبيق قريباً',
  trackBody: 'تطبيق وايت لاين قادم قريباً.',
  downloadOn: 'حمّل من',
  getItOn: 'متوفر على',
  downloadApp: 'تم',
  mobileAppAlt: 'تطبيق وايت لاين للجوال',
  closeLabel: 'إغلاق نافذة الحجز',
  cancelTitle: 'تريد تلغي الحجز؟',
  cancelBody: 'راح تنحذف كل البيانات اللي دخلتها. متأكد تبي تغادر؟',
  cancelKeepBooking: 'كمّل الحجز',
  cancelYes: 'نعم، إلغاء',
  redirectingTitle: 'جارٍ التحويل إلى الدفع',
  redirectingBody: 'جارٍ تحويلك بأمان إلى صفحة الدفع. يرجى عدم إغلاق هذه النافذة.',
  flightLookupLoading: 'جارٍ البحث عن الرحلة…',
  flightLookupDateNeeded: 'أدخل تاريخ الرحلة للبحث عنها.',
  flightLookupNotFound: (num: string) => `لم يُعثر على رحلة ${num} في هذا التاريخ.`,
  flightLookupUnavailable: 'بيانات الرحلات غير متاحة مؤقتاً. حاول مجدداً.',
  flightLookupValidationError: 'أدخل رقم رحلة IATA صحيحاً (مثال: SV123 أو EK505).',
  flightLookupNetworkError: 'خطأ في الشبكة. تحقق من اتصالك وحاول مجدداً.',
  flightAutoFillTitle: 'تعبئة البيانات من معلومات الرحلة؟',
  flightAutoFillBody: 'وجدنا رحلتك. اختر الآن وقت الاستقبال المناسب بعد الهبوط.',
  flightAutoFillConfirm: 'تطبيق',
  pickupEstimatorTitle: 'لتحديد وقت الاستقبال، اختر متى تريد وصول السائق بعد الهبوط',
  pickupEstimatorByMinutes: 'بالدقائق',
  pickupEstimatorByTime: 'بالوقت',
  pickupEstimatorAfterArrival: (min: number) => `${min} دقيقة بعد الوصول`,
  pickupEstimatorConfirm: 'تحديد وقت الاستقبال',
  pickupEstimatorBack: 'رجوع',
}

export type BookingDialogCopy = typeof en
export const bookingDialogCopy: Record<LangCode, BookingDialogCopy> = { en, ar }
